version: "3.8"

x-app-build: &app-build
  context: .
  dockerfile: Dockerfile

services:
  mysql:
    image: mysql:8.0
    container_name: borehole_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-borehole_db}
      MYSQL_USER: ${MYSQL_USER:-borehole_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: *app-build
    image: borehole-backend:latest
    container_name: borehole_backend
    command: ["python3", "-m", "src.api.app"]
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./scripts:/app/scripts:ro
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER:-borehole_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-borehole_db}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_PORT=5000
      - API_HOST=0.0.0.0
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  pipeline:
    build: *app-build
    image: borehole-pipeline:latest
    container_name: borehole_pipeline
    command: ["python3", "-m", "src.main"]
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./output:/app/output
      - ./secrets:/app/secrets:ro
    environment:
      - BOX_CONFIG=/app/secrets/box_config.json
      - AWS_REGION=${AWS_REGION:-us-east-2}
      - CONFIG_FILE=/app/config/config.yaml
      - PYTHONPATH=/app
      - BOX_PARENT_FOLDER_ID=${BOX_PARENT_FOLDER_ID}
      - BOX_MINE_AREAS_JSON=${BOX_MINE_AREAS_JSON:-}
      - PIPELINE_REFRESH_SECONDS=${PIPELINE_REFRESH_SECONDS:-600}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MAPBOX_TOKEN: ${MAPBOX_TOKEN:-}
    image: borehole-frontend:latest
    container_name: borehole_frontend
    ports:
      - "3000:80"
    environment:
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: borehole_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    networks:
      - default

volumes:
  mysql_data:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/letsencrypt
  certbot-www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/certbot

networks:
  default:
    driver: bridge
